### ISSUE TITLE
Oops this routine crushes all colours that are not printable characters

### ISSUE THREAD

**Issue by lilithebowman** [adamlwgriffiths/qbasic-fractal#3]
https://github.com/adamlwgriffiths/qbasic-fractal/blob/a38069400566a5bda8d276622bd45141760c0776/MANDELBR.BAS#L52

![PXL_20210107_141523183](https://user-images.githubusercontent.com/1637212/103902800-0952c500-50c9-11eb-8432-b99882e4b868.jpg)

**Comment by lilithebowman** [comment]
Nope... just my routine to read it needed to DIM the colour as an INTEGER before reading. Works great!

**Comment by adamlwgriffiths** [comment]
Just a thought for something else to do, once the image is rendered you might be able to rotate the palette and animate the image.
https://youtu.be/LUbrzg21X9c?t=44

**Comment by lilithebowman** [comment]
> 
> 
> Just a thought for something else to do, once the image is rendered you might be able to rotate the palette and animate the image.
> https://youtu.be/LUbrzg21X9c?t=44

Yeah! I almost forgot that I found a faster way to do palette changes in QBASIC. Basically you can use the OUT command to send to the interrupt for VGA palette changes.

I just didn't get around to that one before I forgot about it again 😆
